backend:
  image: kiva-backend:latest
  replicas: 1
  port: 5000
  mongoUri: "mongodb://mongo:27017/kiva-blog"
  jwtSecret: "kivasecretkey123"
  frontendUrl: "http://localhost"
frontend:
  image: kiva-frontend:v2
  replicas: 1
  nodePort: 30080